accounts/urls.py
from django.conf.urls import url
import django.contrib.auth.views

import accounts.views


urlpatterns = [

    url( r'^new_account$', accounts.views.new_account, name= 'new_account' ),
    url( r'^login$', accounts.views.login, name= 'login' ),
    url( r'^logout$', django.contrib.auth.views.logout, name= 'logout' ),
    url( r'^user/(?P<username>\w+)$', accounts.views.user_page, name= 'user_page' ),

        # Add/Remove Moderator Rights
    url( r'^set_moderator/confirm/(?P<username>\w+)$', accounts.views.set_moderator_confirm, name= 'set_moderator_confirm' ),
    url( r'^set_moderator/(?P<username>\w+)$', accounts.views.set_moderator, name= 'set_moderator' ),

        # Remove Account
    url( r'^remove/confirm/(?P<username>\w+)$', accounts.views.remove_user_confirm, name= 'remove_confirm' ),
    url( r'^remove/(?P<username>\w+)$', accounts.views.remove_user, name= 'remove' ),

        # Disable Account
    url( r'^disable/confirm/(?P<username>\w+)$', accounts.views.disable_user_confirm, name= 'disable_confirm' ),
    url( r'^disable/(?P<username>\w+)$', accounts.views.disable_user, name= 'disable' ),

        # Change Password
    url( r'^change_password$', django.contrib.auth.views.password_change, { 'template_name': 'accounts/change_password.html', 'post_change_redirect': 'accounts:password_changed' }, name= 'change_password' ),
    url( r'^password_changed$', accounts.views.password_changed, name= 'password_changed' ),

       # Private Messages
    url( r'^message/send/(?P<username>\w+)$', accounts.views.message_send, name= 'message_send' ),
    url( r'^message/all/$', accounts.views.message_all, name='message_all' ),
    url( r'^message/open/(?P<messageId>\w+)$', accounts.views.message_open, name= 'message_open' ),
    url( r'^message/remove_confirm/(?P<messageId>\w+)$', accounts.views.message_remove_confirm, name= 'message_remove_confirm' ),
    url( r'^message/remove/(?P<messageId>\w+)$', accounts.views.message_remove, name= 'message_remove' ),
]

init_django/urls.py
"""
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
"""
from django.conf.urls import include, url
from django.contrib import admin

import start_app.views
import accounts.urls


urlpatterns = [

    url( r'^$', start_app.views.home, name= 'home' ),

    url( r'^accounts/', include( accounts.urls, namespace= 'accounts', app_name= 'accounts' ) ),
    url( r'^admin/', include( admin.site.urls ) ),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.utils import timezone
from django.core.urlresolvers import reverse


class Account( AbstractUser ):

    is_moderator = models.BooleanField( default= False )

    def get_url(self):
        return reverse( 'accounts:user_page', args= [ self.username ] )

    def has_moderator_rights(self):
        if self.is_staff or self.is_moderator:
            return True

        return False

    def how_many_unread_messages(self):
        return self.privatemessage_set.filter( has_been_read= False ).count()

    def __str__(self):
        return self.username


class PrivateMessage( models.Model ):

    receiver = models.ForeignKey( settings.AUTH_USER_MODEL )
    sender = models.ForeignKey( settings.AUTH_USER_MODEL, related_name= 'sender' )
    title = models.TextField( max_length= 100 )
    content = models.TextField( max_length= 500 )
    date_created = models.DateTimeField( help_text= 'Date Created', default= timezone.now )
    has_been_read = models.BooleanField( default= False )

    def __str__(self):
        return self.title

    def get_url(self):
        return reverse( 'accounts:message_open', args= [ self.id ] )

    def get_date_created_number(self):
        """
            Time since the date it was created until the current time.
            Returns a float, useful for comparisons/sorting/etc.
        """
        diff = timezone.now() - self.date_created

        return diff.total_seconds()

    class Meta:
        ordering = [ '-date_created' ]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.html import strip_tags


class FixUserCreationForm( UserCreationForm ):
    """
        The django form has the User hard-coded (so doesn't work with custom user models)

        Just change the parts where the User is hard-coded
    """
    def clean_username(self):

        userModel = get_user_model()
        username = self.cleaned_data[ "username" ]

        try:
            userModel.objects.get( username= username )

        except userModel.DoesNotExist:
            return username

        raise forms.ValidationError( self.error_messages[ 'duplicate_username' ] )


class MyUserCreationForm( FixUserCreationForm ):

    email = forms.EmailField( required= True )

    class Meta:

        model = get_user_model()
        fields = ( 'username', 'email', 'password1', 'password2' )

    def clean_email( self ):
        """
            Check if there's already an user with that email
        """
        userModel = get_user_model()
        email = self.cleaned_data[ 'email' ]

        try:
            userModel.objects.get( email= email )

        except userModel.DoesNotExist:
            return email

        else:
            raise ValidationError( 'An account with that email already exists.' )

    def save( self, commit= True ):

        user = super( MyUserCreationForm, self ).save( commit= False )
        user.email = self.cleaned_data[ 'email' ]

        if commit:
            user.save()

        return user


class PrivateMessageForm( forms.Form ):

    title = forms.CharField( max_length= 100 )
    content = forms.CharField( max_length= 500, widget= forms.Textarea )

    def clean_title(self):
        return strip_tags( self.cleaned_data[ 'title' ] )

    def clean_content(self):
        return strip_tags( self.cleaned_data[ 'content' ] )

accounts/views.py
from django.contrib.auth import get_user_model
from django.http import Http404, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login as django_login
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from accounts.forms import MyUserCreationForm, PrivateMessageForm
from accounts.models import PrivateMessage
from accounts.decorators import must_be_staff, must_be_moderator

from init_django import utilities


def new_account( request ):
    """
        Create a new user account.
    """
    if request.method == 'POST':

        form = MyUserCreationForm( request.POST )

        if form.is_valid():

            form.save()
            utilities.add_message( request, "User '{}' created!".format(  form.cleaned_data[ 'username' ] ) )

            return HttpResponseRedirect( reverse( 'accounts:login' ) )

    else:
        form = MyUserCreationForm()

    context = {
        'form': form
    }

    return render( request, 'accounts/new_account.html', context )


def login( request ):
    """
        Login an account.
    """
    context = {}
    utilities.get_messages( request, context )

    return django_login( request, 'accounts/login.html', extra_context= context )


def user_page( request, username ):
    """
        The user page has information about an user account.
        Also where you can change some settings (like the password).
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    context = {
        'pageUser': user,
        'unreadMessages': user.how_many_unread_messages()
    }

    utilities.get_messages( request, context )

    return render( request, 'accounts/user_page.html', context )


@login_required
def message_send( request, username ):
    """
        Send a private message to another user.
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( 'Invalid username.' )


    if request.method == 'POST':
        form = PrivateMessageForm( request.POST )

        if form.is_valid():

            title = form.cleaned_data[ 'title' ]
            content = form.cleaned_data[ 'content' ]
            message = PrivateMessage( receiver= user, sender= request.user, title= title, content= content )
            message.save()

            utilities.add_message( request, 'Message sent to {}!'.format( user ) )

            return HttpResponseRedirect( user.get_url() )

    else:
        form = PrivateMessageForm()

    context = {
        'form': form,
        'receiver': user
    }

    return render( request, 'accounts/send_message.html', context )


@login_required
def message_all( request ):
    """
        Show a list with all the private messages that were sent to the account.
    """
    messages = request.user.privatemessage_set.all()

    paginator = Paginator( messages, 10 )
    page = request.GET.get( 'page' )

    try:
        paginatedMessages = paginator.page( page )

    except PageNotAnInteger:
        paginatedMessages = paginator.page( 1 )  # first page

    except EmptyPage:
        paginatedMessages = paginator.page( paginator.num_pages )  # last page

    context = {
        'messages': paginatedMessages
    }
    utilities.get_messages( request, context )

    return render( request, 'accounts/check_messages.html', context )


@login_required
def message_open( request, messageId ):
    """
        Open a particular private message.
    """
    try:
        message = request.user.privatemessage_set.get( id= messageId )

    except PrivateMessage.DoesNotExist:
        raise Http404( "Couldn't find that message." )

    if not message.has_been_read:
        message.has_been_read = True
        message.save( update_fields= [ 'has_been_read' ] )

    context = {
        'private_message': message
    }

    return render( request, 'accounts/open_message.html', context )


@login_required
def message_remove_confirm( request, messageId ):
    """
        Confirm the message removal.
    """
    try:
        message = request.user.privatemessage_set.get( id= messageId )

    except PrivateMessage.DoesNotExist:
        raise Http404( "Didn't find the message." )

    else:
        context = {
            'private_message': message
        }

        return render( request, 'accounts/remove_message.html', context )


@login_required
def message_remove( request, messageId ):
    """
        Remove a private message.
    """
    try:
        message = request.user.privatemessage_set.get( id= messageId )

    except PrivateMessage.DoesNotExist:
        raise Http404( "Message doesn't exist." )

    message.delete()
    utilities.add_message( request, 'Message removed!' )

    return HttpResponseRedirect( reverse( 'accounts:message_all' ) )


@must_be_staff
def set_moderator_confirm( request, username ):
    """
        Confirm giving/removing moderator rights to/from an user.
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    else:
        context = {
            'user_to_change': user
        }
        return render( request, 'accounts/change_moderator.html', context )


@must_be_staff
def set_moderator( request, username ):
    """
        Give/remove moderator rights from an account.
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    user.is_moderator = not user.is_moderator
    user.save( update_fields= [ 'is_moderator' ] )

    if user.is_moderator:
        message = "'{}' is now a moderator.".format( user )

    else:
        message = "'{}' is not a moderator anymore.".format( user )

    utilities.add_message( request, message )

    return HttpResponseRedirect( user.get_url() )


def password_changed( request ):
    """
        Inform that the password has been changed, and redirect to home.
    """
    utilities.add_message( request, 'Password changed!' )

    return HttpResponseRedirect( reverse( 'home' ) )


@must_be_staff
def remove_user_confirm( request, username ):
    """
        Confirm an user removal.
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    context = {
        'user_to_remove': user
    }

    return render( request, 'accounts/remove_user.html', context )


@must_be_staff
def remove_user( request, username ):
    """
        Remove an user account (also removes everything associated with it).
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    else:
        utilities.add_message( request, "'{}' user removed!".format( user ) )
        user.delete()

        return HttpResponseRedirect( reverse( 'home' ) )


@must_be_moderator
def disable_user_confirm( request, username ):
    """
        Confirm the enabling/disabling of an user account.
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    else:
        context = {
            'user_to_disable': user
        }

        return render( request, 'accounts/disable_user.html', context )


@must_be_moderator
def disable_user( request, username ):
    """
        Enable/disable an user account.
        If the account is disabled, the user won't be able to login.
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    else:
        value = not user.is_active

            # only other staff users can enable/disable staff users
        if user.is_staff:
            if request.user.is_staff:
                user.is_active = value
                user.save( update_fields= [ 'is_active' ] )

            else:
                return HttpResponseForbidden( "Can't disable a staff member." )

        else:
            user.is_active = value
            user.save( update_fields= [ 'is_active' ] )


        if value:
            message = "'{}' account is now active.".format( user )

        else:
            message = "'{}' account is now disabled.".format( user )

        utilities.add_message( request, message )

        return HttpResponseRedirect( user.get_url() )

templates/accounts/change_moderator.html
{% extends "base.html" %}
{% load accounts %}

{% block content %}

{% if user_to_change.is_moderator %}
    <h2>Remove moderator rights from {{ user_to_change|account_name }}?</h2>
{% else %}
    <h2>Give moderator rights to {{ user_to_change|account_name }}?</h2>
{% endif %}

<p>
    <a href="{% url 'accounts:set_moderator' user_to_change.username %}">Yes</a>
    <a href="{{ user_to_change.get_url }}">No</a>
</p>

{% endblock %}

templates/accounts/change_password.html
{% extends "base.html" %}

{% block content %}

<h2>Change password</h2>

{% if form.errors %}
    <p>{{ form.errors }}</p>
{% endif %}

<form method="post" action="{% url 'accounts:change_password' %}">
    {% csrf_token %}

    <table>
        <tr>
            <td>{{ form.old_password.label_tag }}</td>
            <td>{{ form.old_password }}</td>
        </tr>
        <tr>
            <td>{{ form.new_password1.label_tag }}</td>
            <td>{{ form.new_password1 }}</td>
        </tr>
        <tr>
            <td>{{ form.new_password2.label_tag }}</td>
            <td>{{ form.new_password2 }}</td>
        </tr>
    </table>

    <input type="submit" value="change" />
    <input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

templates/accounts/check_messages.html
{% extends "base.html" %}
{% load humanize %}
{% load accounts %}
{% load static %}


{% block scripts %}
    <script type="text/javascript" src="{% static 'js/check_messages.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/tooltip.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/sort_table.js' %}"></script>
{% endblock %}


{% block content %}

<h2>Private messages</h2>

{% if messages %}

    <table id="CheckMessagesTable" class="SortTable">
        <thead>
            <tr>
                <th class="SortTable-sortable">from</th>
                <th class="SortTable-sortable">title</th>
                <th class="SortTable-sortable" data-initial-sort="ascending">date</th>
            </tr>
        </thead>

        <tbody>
        {% for message in messages %}
            <tr class="clickableRow contentPreview" data-url="{{ message.get_url }}" data-content="{{ message.content|linebreaksbr|truncatewords:50 }}">
                <td data-value="{{ message.sender }}">
                    {% if not message.has_been_read %}
                        <span class="red" title="Unread message!">!</span>
                    {% endif %}

                    {{ message.sender|account_name }}
                </td>
                <td data-value="{{ message.title.strip|truncatewords:25 }}">{{ message.title|truncatewords:25 }}</td>
                <td data-value="{{ message.get_date_created_number }}">{{ message.date_created|naturaltime }}</td>
                <td><a href="{% url 'accounts:message_remove_confirm' message.id %}" title="Remove Message">X</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if messages.has_previous %}
        <a href="{{ request.path|urlencode }}?page={{ messages.previous_page_number }}">previous</a>
    {% endif %}
    {% if messages.number %}
        <span>Page {{ messages.number }} of {{ messages.paginator.num_pages }}</span>
    {% endif %}
    {% if messages.has_next %}
        <a href="{{ request.path|urlencode }}?page={{ messages.next_page_number }}">next</a>
    {% endif %}
{% else %}
    <p>No messages.</p>
{% endif %}

{% endblock %}

templates/accounts/disable_user.html
{% extends "base.html" %}
{% load accounts %}

{% block content %}

{% if user_to_disable.is_active %}
    <h2>Disable user: {{ user_to_disable|account_name }}?</h2>
{% else %}
    <h2>Enable user: {{ user_to_disable|account_name }}?</h2>
{% endif %}

<p>
    <a href="{% url 'accounts:disable' user_to_disable.username %}">Yes</a>
    <a href="{{ user_to_disable.get_url }}">No</a>
</p>

{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}

{% block content %}

<h1>Login</h1>

{% if form.errors %}
    <p>Wrong username/password.</p>
{% endif %}

<form method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}

    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>

    <input type="submit" value="login" />
    <input type="hidden" name="next" value="{{ next }}" />
</form>

<br /><br />

<p>
    <a href="{% url 'accounts:new_account' %}">Create a new account.</a>
</p>


{% endblock %}

templates/accounts/new_account.html
{% extends "base.html" %}

{% block content %}

    <h1>Create a new user</h1>

    {% if form.errors %}
        <table>
            {% for field in form %}
                <tr>
                    <td>{{ field.name }}</td>
                    <td>{{ field.errors }}</td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}

    <form method="post" action="{% url 'accounts:new_account' %}">
        {% csrf_token %}

        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.email.label_tag }}</td>
                <td>{{ form.email }}</td>
            </tr>
            <tr>
                <td>{{ form.password1.label_tag }}</td>
                <td>{{ form.password1 }}</td>
            </tr>
            <tr>
                <td>{{ form.password2.label_tag }}</td>
                <td>{{ form.password2 }}</td>
            </tr>
        </table>

        <input type="submit" value="create" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>

{% endblock %}

templates/accounts/open_message.html
{% extends "base.html" %}
{% load humanize %}
{% load accounts %}

{% block content %}

<p>From {{ private_message.sender|account_name }} {{ private_message.date_created|naturaltime }}</p>

<h2 id="PrivateMessage-title">{{ private_message.title }}</h2>

<p>{{ private_message.content|linebreaksbr }}</p>

<a href="{% url 'accounts:message_send' private_message.sender.username %}">reply</a>
<a href="{% url 'accounts:message_all' %}">back</a>

{% endblock %}

templates/accounts/remove_message.html
{% extends "base.html" %}
{% load humanize %}
{% load accounts %}

{% block content %}

<p>From {{ private_message.sender|account_name }} {{ private_message.date_created|naturaltime }}</p>

<h2 id="PrivateMessage-title">{{ private_message.title }}</h2>

<p>{{ private_message.content|linebreaksbr }}</p>


<p>Remove private message? <a href="{% url 'accounts:message_remove' private_message.id %}">Yes</a> <a href="{% url 'accounts:message_all' %}">No</a></p>

{% endblock %}

templates/accounts/remove_user.html
{% extends "base.html" %}
{% load accounts %}

{% block content %}
<h2>Remove user: {{ user_to_remove|account_name }}?</h2>

<p>
    <a href="{% url 'accounts:remove' user_to_remove.username %}">Yes</a>
    <a href="{{ user_to_remove.get_url }}">No</a>
</p>
{% endblock %}

templates/accounts/send_message.html
{% extends "base.html" %}
{% load accounts %}

{% block content %}

<h2>Send message to {{ receiver|account_name }}</h2>

{% if form.errors %}
    <p>{{ form.errors }}</p>
{% endif %}

<form method="post" action="{% url 'accounts:message_send' receiver.username %}">
    {% csrf_token %}

    <table>
        <tr>
            <td>{{ form.title.label_tag }}</td>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <td>{{ form.content.label_tag }}</td>
            <td>{{ form.content }}</td>
        </tr>
    </table>

    <input type="submit" value="send" />
    <input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

templates/accounts/user_page.html
{% extends "base.html" %}
{% load humanize %}
{% load accounts %}

{% block content %}

    <h2>
        {{ pageUser|account_name }}

        <ul class="horizontalList">
            {% if user.is_moderator or user.is_staff %}
            <li>
                <a href="{% url 'accounts:disable_confirm' pageUser.username %}">
                    {% if pageUser.is_active %}
                        disable
                    {% else %}
                        enable
                    {% endif %}
                </a>
            </li>
            {% endif %}

            {% if user.is_staff %}
            <li>
                <a href="{% url 'accounts:set_moderator_confirm' pageUser.username %}">
                    {% if pageUser.is_moderator %}
                        un-mod
                    {% else %}
                        mod
                    {% endif %}
                </a>
            </li>
            <li>
                <a href="{% url 'accounts:remove_confirm' pageUser.username %}">remove</a>
            </li>
            {% endif %}
        </ul>
    </h2>

    <p>User since: {{ pageUser.date_joined }} ({{ pageUser.date_joined|naturaltime }})</p>

    {% if user.is_authenticated %}
        <ul>
        {% if user.username == pageUser.username %}
            <li>
                <a href="{% url 'accounts:message_all' %}">See messages
                    {% if unreadMessages %}
                        (<em>{{ unreadMessages }}</em> unread)
                    {% endif %}
                </a>
            </li>
            <li><a href="{% url 'accounts:change_password' %}">change password</a></li>
        {% else %}
            <li><a href="{% url 'accounts:message_send' pageUser.username %}">Send private message</a></li>
        {% endif %}
        </ul>
    {% endif %}


{% endblock %}